export const accessTableData = [
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
  {
    img: "malePrincipal",
    operator: "Mahbub Rahman",
    designation: "Assistant Teacher",
    contact: "(406) 555-0120",
    access: "",
  },
];
