export const promotionTableData = [
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
  {
    class: "Class-1",
    exam: "Yearly",
    session: "2022",
    status: "Promoted",
  },
];

export const promotedTableTada = [
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    status: "Promoted",
    promoted: "Class - 1",
  },
];
