export const resultTableData = [
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
  {
    roll: "1",
    name: "Mahmudul Haque",
    position: "1st",
    grade: "A",
    gpa: "5.00",
  },
];
