export const studentInfoTableData = [
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
  {
    name: "Wade Warren",
    roll: "01",
    parentName: "Parent Name",
    location: "Rajshahi",
    contact: "016555-0120",
  },
];
