export const classRoutineData = [
  {
    id: "1",
    time: "7:00 - 7:40 am",
    day: "Saturday",
    subject: [
      { subjectName: "Bangla", teacher: "Wade Warren" },
      { subjectName: "English", teacher: "Wade Warren" },
      { subjectName: "Math", teacher: "Wade Warren" },
      { subjectName: "Physics", teacher: "Wade Warren" },
      { subjectName: "Chemistry", teacher: "Wade Warren" },
      { subjectName: "Biology", teacher: "Wade Warren" },
    ],
    teacher: "Wade Warren",
  },
  {
    id: "2",
    time: "7:00 - 7:40 am",
    day: "Saturday",
    subject: [
      { subjectName: "Bangla", teacher: "Wade Warren" },
      { subjectName: "English", teacher: "Wade Warren" },
      { subjectName: "Math", teacher: "Wade Warren" },
      { subjectName: "Physics", teacher: "Wade Warren" },
      { subjectName: "Chemistry", teacher: "Wade Warren" },
      { subjectName: "Biology", teacher: "Wade Warren" },
    ],
  },
  {
    id: "3",
    time: "7:00 - 7:40 am",
    day: "Saturday",
    subject: [
      { subjectName: "Bangla", teacher: "Wade Warren" },
      { subjectName: "English", teacher: "Wade Warren" },
      { subjectName: "Math", teacher: "Wade Warren" },
      { subjectName: "Physics", teacher: "Wade Warren" },
      { subjectName: "Chemistry", teacher: "Wade Warren" },
      { subjectName: "Biology", teacher: "Wade Warren" },
    ],
    teacher: "Wade Warren",
  },
  {
    id: "4",
    time: "7:00 - 7:40 am",
    day: "Saturday",
    subject: [
      { subjectName: "Bangla", teacher: "Wade Warren" },
      { subjectName: "English", teacher: "Wade Warren" },
      { subjectName: "Math", teacher: "Wade Warren" },
      { subjectName: "Physics", teacher: "Wade Warren" },
      { subjectName: "Chemistry", teacher: "Wade Warren" },
      { subjectName: "Biology", teacher: "Wade Warren" },
    ],
    teacher: "Wade Warren",
  },
  {
    id: "5",
    time: "7:00 - 7:40 am",
    day: "Saturday",
    subject: [
      { subjectName: "Bangla", teacher: "Wade Warren" },
      { subjectName: "English", teacher: "Wade Warren" },
      { subjectName: "Math", teacher: "Wade Warren" },
      { subjectName: "Physics", teacher: "Wade Warren" },
      { subjectName: "Chemistry", teacher: "Wade Warren" },
      { subjectName: "Biology", teacher: "Wade Warren" },
    ],
    teacher: "Wade Warren",
  },
  {
    id: "6",
    time: "7:00 - 7:40 am",
    day: "Saturday",
    subject: [
      { subjectName: "Bangla", teacher: "Wade Warren" },
      { subjectName: "English", teacher: "Wade Warren" },
      { subjectName: "Math", teacher: "Wade Warren" },
      { subjectName: "Physics", teacher: "Wade Warren" },
      { subjectName: "Chemistry", teacher: "Wade Warren" },
      { subjectName: "Biology", teacher: "Wade Warren" },
    ],
    teacher: "Wade Warren",
  },
];

const examRoutineData = [
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
  {
    date: "24/07/2022",
    day: "Sunday",
    time: "10:00 am - 01:00 pm",
    subject: "Bangla 1st Paper",
  },
];
